ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_patient_fx
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_provider_fx
ALTER TABLE DrugTreatment DROP CONSTRAINT FK_DrugTreatment_ID
ALTER TABLE Surgery DROP CONSTRAINT FK_Surgery_ID
ALTER TABLE Radiology DROP CONSTRAINT FK_Radiology_ID
DROP TABLE PATIENT CASCADE
DROP TABLE TREATMENT CASCADE
DROP TABLE DrugTreatment CASCADE
DROP TABLE PROVIDER CASCADE
DROP TABLE Surgery CASCADE
DROP TABLE Radiology CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
